Makes full template power available to blog posts.
Previously, I got weired errors when using e.g. `{% url path %}`
in blog posts:

```
*** Error while building
'__CACTUS_SITE__'
Traceback (most recent call last):
...
File "/usr/local/lib/python2.7/dist-packages/Cactus-3.3.2-py2.7.egg/cactus/template_tags.py", line 52, in url
    site = context['__CACTUS_SITE__']
  File "/usr/local/lib/python2.7/dist-packages/Django-1.6.11-py2.7.egg/django/template/context.py", line 56, in __getitem__
    raise KeyError(key)
KeyError: '__CACTUS_SITE__'
```

It turns out that `getNode` needs the full site context
to work probably.
Therefore this commit creates the site context and adds it to all postContexts.
Now I can use `{% url path %}` and the likes in my blog posts.